services:
  redstonecore:
    image: redstonecore-agent:local
    container_name: redstonecore-test
    restart: unless-stopped
    network_mode: host

    environment:
      - RSC_LICENSE_KEY=RSC-LFRP-IXZ3-QLHL-QIQ8

    volumes:
      - ./data:/data
      - ./config:/config

    deploy:
      resources:
        limits:
          memory: 4G
